name: Animeshon Documentation [development]

env:
  # Environment
  ENVIRONMENT: development

  # Google Cloud Credentials
  PROJECT_ID:             ${{ secrets.TIER_2_SERVICES_PROJECT }}
  KUBERNETES_CREDENTIALS: ${{ secrets.TIER_2_SERVICES_KUBERNETES_CREDENTIALS }}
  REGISTRY_CREDENTIALS:   ${{ secrets.TIER_2_SERVICES_REGISTRY_CREDENTIALS }}

  US_CLUSTER: ${{ secrets.TIER_2_SERVICES_US_CLUSTER }}
  US_ZONE:    ${{ secrets.TIER_2_SERVICES_US_ZONE }}

on:
  push:
    branches-ignore: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository code
        uses: actions/checkout@v3
        with: { submodules: true }

      - name: Build and push Docker images to Google Cloud Registry
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ env.REGISTRY_CREDENTIALS }}
          registry: gcr.io
          repository: ${{ env.PROJECT_ID }}/web-ui/docs
          tags: latest,${{ github.event.inputs.sha || github.sha }}
          tag_with_ref: true
          tag_with_sha: true

  deployment:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository code
        uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3

      - name: Install and configure Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ env.KUBERNETES_CREDENTIALS }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate to kubernetes (US)
        run: |-
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials "$US_CLUSTER" --zone "$US_ZONE"

      - name: Install or upgrade the Helm chart
        run: |-
          helm upgrade docs ./helm/charts/docs  \
            --install \
            --values    helm/docs.yaml \
            --values    helm/docs.${{ env.ENVIRONMENT }}.yaml \
            --set       image.tag=${{ github.event.inputs.sha || github.sha }} \
            --namespace web-ui
